# 정적 컨텐츠를 GitHub 페이지에 배포하기 위한 간단한 워크플로우
이름.: 페이지에 정적 컨텐츠 배포

위에:
  # 기본 분기를 대상으로 푸시 시 실행
 밀다:
 나뭇가지: ["메인"]

  # 작업 탭에서 이 워크플로를 수동으로 실행할 수 있습니다.
 워크플로_dispatch:

# GitHub 페이지에 배포할 수 있도록 GITHUB_TOKEN의 권한을 설정합니다.
허가증:
 내용물: read
 페이지: 쓰기
 아이드 토큰: 쓰기

# 진행 중인 실행과 최근 대기열 사이에 대기열에 포함된 실행을 건너뛰고 하나의 동시 배포만 허용합니다.
# 그러나 이러한 프로덕션 배포가 완료되도록 하려면 진행 중인 실행을 취소하지 마십시오.
동시성:
 그룹.: "페이지"
 진행률 취소: 거짓의

일:
  # 우리는 이제 막 배포하기 때문에 단일 배포 작업
 배치하다:
 환경:
 이름.: 깃허브-페이지
 url: ${steps.deployment.outputs.page_url }
 뜀박질의: 우분투-latest
 걸음걸이:
 - 이름.: 체크아웃
 사용하다: 동작/checkout@v4
 - 이름.: 설정 페이지
 사용하다: 작업/구성-pages@v5
 - 이름.: 아티팩트 업로드
 사용하다: 작업/upload-페이지-artifact@v3
 다음과 함께:
 # 전체 리포지토리 업로드
 path: '.'
 - 이름: GitHub 페이지에 배포
 id: 배포
 사용하다: 작업/deploy-pages@v4
